language: node_js
node_js:
  - 10
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master

after_success:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "receipt-split"
  skip_cleanup: true
  local_dir: build
