env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=isaaclo1234/receipt-split

stages:
- deploy

branches:
  only:
  - master

jobs:
  include:
  - stage: test
    language: node_js
    node_js: 10

    cache:
      directories:
      - node_modules

    script:
    - npm run test

  - stage: build
    language: ruby

    services:
    - docker

    before_install:
    - docker build -t receipt-split .
    - docker build -t $REPO:$COMMIT .
    - docker run -d -p 5000:5000 --name receipt-split $REPO:$COMMIT

    script:
    - docker ps | grep -q receipt-split

    after_success:
    - echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH ; fi`
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO

  - stage: deploy
    language: python
    cache:
      directories:
      - roles

    before_install:
    - openssl aes-256-cbc -K $encrypted_06826a922d57_key -iv $encrypted_06826a922d57_iv -in travis.pem.enc -out travis.pem -d
    - (echo "[prod]" && echo "$ANSIBLE_HOST") > inventory.prod
    - chmod 600 travis.pem

    install:
    - pip install ansible
    - ansible-galaxy install -r requirements.yml

    script:
    - ansible-playbook site.yml -i inventory.prod --private-key travis.pem -d
