language: node_js
node_js:
  - 10
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master

after_success:
  - npm run build

language: bash
services:
  - docker
install:
  - docker build -t receipt-split .
  - docker run -d -p 5000:5000 -name receipt-split receipt-split

script:
  - docker ps | grep -q receipt-split
