env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

jobs:
  include:

    - language: node_js
      node_js: 10
      cache:
        directories:
          - "node_modules"
      branches:
        only:
        - master
      after_success:
        - npm run build

    - language: generic
      # requires env vars
      # DOCKER_EMAIL
      # DOCKER_USER
      # DOCKER_PASS
      services:
        - docker
      install:
        - docker build -t receipt-split .
        - docker run -d -p 5000:5000 --name receipt-split receipt-split
      script:
        - docker ps | grep -q receipt-split
      after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - export REPO=isaaclo1234/receipt-split
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
        - docker build -f Dockerfile -t $REPO:$COMMIT .
        - docker tag $REPO:$COMMIT $REPO:$TAG
        - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
        - docker push $REPO
