#!/usr/bin/env ansible-playbook

- import_playbook: ./playbooks/postgres.yml

- import_playbook: ./playbooks/docker.yml

- import_playbook: ./playbooks/letsencrypt.yml

- import_playbook: ./playbooks/nginx.yml
