"""empty message

Revision ID: 0ccbcfd3835b
Revises: 7420fed93f54
Create Date: 2020-08-06 16:37:05.826724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ccbcfd3835b'
down_revision = '7420fed93f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_total', sa.Float(asdecimal=True), nullable=False))
        batch_op.add_column(sa.Column('left_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('payment_total', sa.Float(asdecimal=True), nullable=False))
        batch_op.add_column(sa.Column('right_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['left_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['right_user_id'], ['id'])
        batch_op.drop_column('to_user_id')
        batch_op.drop_column('owed_amount')
        batch_op.drop_column('from_user_id')
        batch_op.drop_column('paid_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('from_user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('owed_amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('to_user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['from_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['to_user_id'], ['id'])
        batch_op.drop_column('right_user_id')
        batch_op.drop_column('payment_total')
        batch_op.drop_column('left_user_id')
        batch_op.drop_column('balance_total')

    # ### end Alembic commands ###
