"""empty message

Revision ID: 7420fed93f54
Revises: 8bbc8b21fe71
Create Date: 2020-06-22 16:59:29.893412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7420fed93f54'
down_revision = '8bbc8b21fe71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('resolved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
