// export const RECIEPT_LIST_REQUEST = "RECIEPT_LIST_REQUEST";
export const RECIEPT_LIST_SUCCESS = "RECIEPT_LIST_SUCCESS";
export const RECIEPT_LIST_FAIL = "RECIEPT_LIST_FAIL";

// export const RECIEPT_ID_REQUEST = "RECIEPT_ID_REQUEST";
export const RECIEPT_ID_SUCCESS = "RECIEPT_ID_SUCCESS";
export const RECIEPT_ID_FAIL = "RECIEPT_ID_FAIL";

export const RECIEPT_CACHE_SUCCESS = "RECIEPT_CACHE_SUCCESS";
export const RECIEPT_CACHE_FAIL = "RECIEPT_CACHE_FAIL";

// export const RECIEPT_SAVE_REQUEST = "RECIEPT_SAVE_REQUEST";
export const RECIEPT_SAVE_SUCCESS = "RECIEPT_SAVE_REQUEST";
export const RECIEPT_SAVE_FAIL = "RECIEPT_SAVE_FAIL";

export const RECIEPT_SET = "RECIEPT_SET";

export const RECIEPT_SET_NAME = "RECIEPT_SET_NAME";
export const RECIEPT_SET_AMOUNT = "RECIEPT_SET_AMOUNT";
export const RECIEPT_SET_DATE = "RECIEPT_SET_DATE";
export const RECIEPT_ADD_USER = "RECIEPT_ADD_USER";
export const RECIEPT_DELETE_USER = "RECIEPT_DELETE_USER";

// export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAIL = "USER_INFO_FAIL";

export const FRIEND_LIST_SUCCESS = "FRIEND_LIST_SUCCESS";
export const FRIEND_LIST_FAIL = "FRIEND_LIST_FAIL";

export const FRIEND_ADD_SUCCESS = "FRIEND_ADD_SUCCESS";
export const FRIEND_ADD_FAIL = "FRIEND_ADD_FAIL";

export const API_MIDDLEWARE_TYPE = "API_MIDDLEWARE_TYPE";

export const EDIT_DATA_PREPEND = -1;
export const EDIT_DATA_APPEND = -2;
export const EDIT_DATA_DELETE = (i: number) => -1 * i - 3;
export const EDIT_DATA_DELETE_GET_INDEX = (j: number) => -1 * (j + 3);
