"""empty message

Revision ID: 51c5ef3e73c5
Revises: 679c7c2b879a
Create Date: 2020-06-15 00:11:42.993964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c5ef3e73c5'
down_revision = '679c7c2b879a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.execute("UPDATE payment SET archived = false")
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
