"""empty message

Revision ID: 679c7c2b879a
Revises: b7c3dfbc7e2e
Create Date: 2020-06-14 23:47:42.592191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679c7c2b879a'
down_revision = 'b7c3dfbc7e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
