"""empty message

Revision ID: 704f89ce63a2
Revises: 289d7babb5c7
Create Date: 2020-09-14 17:06:42.845315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704f89ce63a2'
down_revision = '289d7babb5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax', sa.Float(asdecimal=True),
                                      nullable=True))

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.execute("UPDATE receipt SET tax = 0")

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.alter_column('tax', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('tax')

    # ### end Alembic commands ###
