"""empty message

Revision ID: 9ae52df3c8bd
Revises: c21b45fa6210
Create Date: 2020-06-16 17:49:02.203241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae52df3c8bd'
down_revision = 'c21b45fa6210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.execute("UPDATE balance SET paid = false")
        batch_op.alter_column('paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
