"""empty message

Revision ID: b7c3dfbc7e2e
Revises: 5f5c3ae3daed
Create Date: 2020-06-14 23:46:19.398471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c3dfbc7e2e'
down_revision = '5f5c3ae3daed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
