"""empty message

Revision ID: bf5d7a6aaeb1
Revises: 5266ffa56fc8
Create Date: 2020-06-17 23:52:51.435240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5d7a6aaeb1'
down_revision = '5266ffa56fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owed_amount', sa.Float(asdecimal=True),
                                      nullable=True))

    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.execute('UPDATE settlement SET owed_amount = 0.0')
        batch_op.alter_column('owed_amount', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.drop_column('owed_amount')

    # ### end Alembic commands ###
