"""empty message

Revision ID: c21b45fa6210
Revises: 1ea754ec9641
Create Date: 2020-06-16 17:34:56.121368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21b45fa6210'
down_revision = '1ea754ec9641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.execute("UPDATE balance SET paid = false")

    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('paid', existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.drop_column('owed_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owed_amount', sa.FLOAT(), nullable=False))

    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
