---

- name: Install docker
  hosts: all
  roles:
    - darkwizard242.docker
  become: yes

- name: Deploy receipt-split docker image from docker hub
  hosts: all
  become: yes
  tasks:
  - name: Install docker-python
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - python-docker
    become: yes

  - name: Create docker receipt-split
    docker_container:
      name: receipt-split
      image: isaaclo1234/receipt-split:latest
      pull: yes
      restart: yes
      restart_policy: always
      recreate: yes

      user: www-data

      state: started

      volumes:
      - /var/run/postgresql/.s.PGSQL.5432:/tmp/.s.PGSQL.5432
      - /var/run/gunicorn.sock:/tmp/gunicorn.sock

      # exposed_ports:
      # - "5000"
      # ports:
      # - "5000:5000"

      env:
        SECRET_KEY: "{{ secret_key }}"
        WSGI_WORKERS: "{{ wsgi_workers }}"
        GUNICORN_SOCK: "unix:/tmp/gunicorn.sock"

        DB_URI: "postgres://{{ postgres_user }}:{{ postgres_pass }}@/receipt_split?host=/tmp"
