---

- name: Create receipt_split database
  hosts: all

  roles:
  - role: geerlingguy.postgresql
    become: yes
    ignore_errors: yes

    name: receipt_split

    # postgresql_python_library: python3-psycopg2

    # postgres_users_no_log: true

    postgresql_service_state: restarted
    postgresql_service_enabled: true

    postgresql_unix_socket_directories:
    - "{{ postgres_sock }}"

    postgresql_global_config_options:
    - option: unix_socket_directories
      value: '{{ postgresql_unix_socket_directories | join(",") }}'
    - option: listen_addresses
      value: ''

    postgresql_hba_entries:
      # - { type: local, database: all, user: "{{ postgres_user }}", auth_method: md5 }
      # - { type: local, database: all, user: "{{ postgres_user }}", auth_method: peer }
    - { type: local, database: all, user: all, auth_method: trust }

    postgresql_databases:
    - name: receipt_split
      login_user: "{{ postgres_user }}"
      login_password: "{{ postgres_pass }}"
      login_unix_socket: "{{ postgres_sock }}"
      port: "{{ postgres_port }}"
      owner: "{{ postgres_user }}"

    postgresql_users:
    - name: "{{ postgres_user }}"
      password: "{{ postgres_pass }}"
      db: receipt_split
      # login_user: '{{ postgres_user }}'
      # login_password: "{{ postgres_pass }}"
      login_unix_socket: "{{ postgres_sock }}"
      port: "{{ postgres_port }}"
