---

- name: Create receipt_split database
  hosts: all
  roles:
  - role: geerlingguy.postgresql
    become: yes
    name: receipt_split

    postgresql_service_state: restarted

    postgresql_global_config_options:
    - option: listen_addresses
      value: ''

    postgresql_unix_socket_directories:
    - "{{ postgres_sock }}"

    postgresql_hba_entries:
    - { type: local, database: all, user: "{{ postgres_user }}", auth_method: md5 }

    postgresql_databases:
    - name: receipt_split
      login_user: "{{ postgres_user }}"
      login_password: "{{ postgres_pass }}"
      login_unix_socket: "{{ postgres_sock }}"
      port: "{{ postgres_port }}"
      owner: "{{ postgres_user }}"

    postgresql_users:
    - name: "{{ postgres_user }}"
      password: "{{ postgres_pass }}"
      db: receipt_split
      login_user: '{{ postgres_user }}'
      login_password: "{{ postgres_pass }}"
      login_unix_socket: "{{ postgres_sock }}"
      port: "{{ postgres_port }}"
